services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: form_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5433"
    restart: unless-stopped

volumes:
  db:
